# coding: utf-8

# flake8: noqa
"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.address import Address
from swagger_client.models.affiliation import Affiliation
from swagger_client.models.affiliation_type import AffiliationType
from swagger_client.models.affiliation_write import AffiliationWrite
from swagger_client.models.check_group_memberships_request import CheckGroupMembershipsRequest
from swagger_client.models.check_group_memberships_response import CheckGroupMembershipsResponse
from swagger_client.models.consent import Consent
from swagger_client.models.consent_purpose import ConsentPurpose
from swagger_client.models.consent_write import ConsentWrite
from swagger_client.models.country import Country
from swagger_client.models.country_write import CountryWrite
from swagger_client.models.error_code import ErrorCode
from swagger_client.models.error_data import ErrorData
from swagger_client.models.error_details import ErrorDetails
from swagger_client.models.gender import Gender
from swagger_client.models.grant_type import GrantType
from swagger_client.models.group import Group
from swagger_client.models.group_member import GroupMember
from swagger_client.models.group_member_write import GroupMemberWrite
from swagger_client.models.group_type import GroupType
from swagger_client.models.group_write import GroupWrite
from swagger_client.models.marital_status import MaritalStatus
from swagger_client.models.metadata import Metadata
from swagger_client.models.national_id import NationalId
from swagger_client.models.org import Org
from swagger_client.models.org_active_status import OrgActiveStatus
from swagger_client.models.org_type import OrgType
from swagger_client.models.org_write import OrgWrite
from swagger_client.models.person import Person
from swagger_client.models.person_relation import PersonRelation
from swagger_client.models.person_relation_grant_to_origin import PersonRelationGrantToOrigin
from swagger_client.models.person_relation_grant_to_target import PersonRelationGrantToTarget
from swagger_client.models.person_relation_type import PersonRelationType
from swagger_client.models.person_write import PersonWrite
from swagger_client.models.preferences import Preferences
from swagger_client.models.relation import Relation
from swagger_client.models.relation_type import RelationType
from swagger_client.models.relation_write import RelationWrite
from swagger_client.models.role import Role
from swagger_client.models.role_assignment import RoleAssignment
from swagger_client.models.role_assignment_write import RoleAssignmentWrite
from swagger_client.models.role_scope import RoleScope
from swagger_client.models.role_write import RoleWrite
from swagger_client.models.search_visibility import SearchVisibility
from swagger_client.models.visibility_preferences import VisibilityPreferences
from swagger_client.models.wrapped_affiliation import WrappedAffiliation
from swagger_client.models.wrapped_check_group_memberships_response import WrappedCheckGroupMembershipsResponse
from swagger_client.models.wrapped_consent import WrappedConsent
from swagger_client.models.wrapped_country import WrappedCountry
from swagger_client.models.wrapped_group import WrappedGroup
from swagger_client.models.wrapped_group_member import WrappedGroupMember
from swagger_client.models.wrapped_int import WrappedInt
from swagger_client.models.wrapped_org import WrappedOrg
from swagger_client.models.wrapped_person import WrappedPerson
from swagger_client.models.wrapped_relation import WrappedRelation
from swagger_client.models.wrapped_role import WrappedRole
from swagger_client.models.wrapped_role_assignment import WrappedRoleAssignment
from swagger_client.models.wrapped_with_meta_array_affiliation import WrappedWithMetaArrayAffiliation
from swagger_client.models.wrapped_with_meta_array_consent import WrappedWithMetaArrayConsent
from swagger_client.models.wrapped_with_meta_array_country import WrappedWithMetaArrayCountry
from swagger_client.models.wrapped_with_meta_array_group import WrappedWithMetaArrayGroup
from swagger_client.models.wrapped_with_meta_array_group_member import WrappedWithMetaArrayGroupMember
from swagger_client.models.wrapped_with_meta_array_org import WrappedWithMetaArrayOrg
from swagger_client.models.wrapped_with_meta_array_person import WrappedWithMetaArrayPerson
from swagger_client.models.wrapped_with_meta_array_relation import WrappedWithMetaArrayRelation
from swagger_client.models.wrapped_with_meta_array_role import WrappedWithMetaArrayRole
from swagger_client.models.wrapped_with_meta_array_role_assignment import WrappedWithMetaArrayRoleAssignment
