# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class CheckGroupMembershipsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'group_uids': 'list[str]'
    }

    attribute_map = {
        'group_uids': 'groupUids'
    }

    def __init__(self, group_uids=None, _configuration=None):  # noqa: E501
        """CheckGroupMembershipsRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._group_uids = None
        self.discriminator = None

        if group_uids is not None:
            self.group_uids = group_uids

    @property
    def group_uids(self):
        """Gets the group_uids of this CheckGroupMembershipsRequest.  # noqa: E501


        :return: The group_uids of this CheckGroupMembershipsRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._group_uids

    @group_uids.setter
    def group_uids(self, group_uids):
        """Sets the group_uids of this CheckGroupMembershipsRequest.


        :param group_uids: The group_uids of this CheckGroupMembershipsRequest.  # noqa: E501
        :type: list[str]
        """

        self._group_uids = group_uids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckGroupMembershipsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckGroupMembershipsRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CheckGroupMembershipsRequest):
            return True

        return self.to_dict() != other.to_dict()
