# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Consent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'app_uid': 'str',
        'is_active': 'bool',
        'last_changed_date': 'datetime',
        'org': 'Org',
        'org_uid': 'str',
        'person': 'Person',
        'person_uid': 'str',
        'process_code': 'str',
        'purpose': 'ConsentPurpose',
        'scopes': 'list[str]',
        'uid': 'str',
        'valid_from': 'datetime',
        'valid_to': 'datetime'
    }

    attribute_map = {
        'app_uid': 'appUid',
        'is_active': 'isActive',
        'last_changed_date': 'lastChangedDate',
        'org': 'org',
        'org_uid': 'orgUid',
        'person': 'person',
        'person_uid': 'personUid',
        'process_code': 'processCode',
        'purpose': 'purpose',
        'scopes': 'scopes',
        'uid': 'uid',
        'valid_from': 'validFrom',
        'valid_to': 'validTo'
    }

    def __init__(self, app_uid=None, is_active=None, last_changed_date=None, org=None, org_uid=None, person=None, person_uid=None, process_code=None, purpose=None, scopes=None, uid=None, valid_from=None, valid_to=None, _configuration=None):  # noqa: E501
        """Consent - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._app_uid = None
        self._is_active = None
        self._last_changed_date = None
        self._org = None
        self._org_uid = None
        self._person = None
        self._person_uid = None
        self._process_code = None
        self._purpose = None
        self._scopes = None
        self._uid = None
        self._valid_from = None
        self._valid_to = None
        self.discriminator = None

        self.app_uid = app_uid
        self.is_active = is_active
        self.last_changed_date = last_changed_date
        if org is not None:
            self.org = org
        self.org_uid = org_uid
        if person is not None:
            self.person = person
        self.person_uid = person_uid
        if process_code is not None:
            self.process_code = process_code
        self.purpose = purpose
        if scopes is not None:
            self.scopes = scopes
        self.uid = uid
        self.valid_from = valid_from
        if valid_to is not None:
            self.valid_to = valid_to

    @property
    def app_uid(self):
        """Gets the app_uid of this Consent.  # noqa: E501


        :return: The app_uid of this Consent.  # noqa: E501
        :rtype: str
        """
        return self._app_uid

    @app_uid.setter
    def app_uid(self, app_uid):
        """Sets the app_uid of this Consent.


        :param app_uid: The app_uid of this Consent.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and app_uid is None:
            raise ValueError("Invalid value for `app_uid`, must not be `None`")  # noqa: E501

        self._app_uid = app_uid

    @property
    def is_active(self):
        """Gets the is_active of this Consent.  # noqa: E501


        :return: The is_active of this Consent.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this Consent.


        :param is_active: The is_active of this Consent.  # noqa: E501
        :type: bool
        """
        if self._configuration.client_side_validation and is_active is None:
            raise ValueError("Invalid value for `is_active`, must not be `None`")  # noqa: E501

        self._is_active = is_active

    @property
    def last_changed_date(self):
        """Gets the last_changed_date of this Consent.  # noqa: E501


        :return: The last_changed_date of this Consent.  # noqa: E501
        :rtype: datetime
        """
        return self._last_changed_date

    @last_changed_date.setter
    def last_changed_date(self, last_changed_date):
        """Sets the last_changed_date of this Consent.


        :param last_changed_date: The last_changed_date of this Consent.  # noqa: E501
        :type: datetime
        """
        if self._configuration.client_side_validation and last_changed_date is None:
            raise ValueError("Invalid value for `last_changed_date`, must not be `None`")  # noqa: E501

        self._last_changed_date = last_changed_date

    @property
    def org(self):
        """Gets the org of this Consent.  # noqa: E501


        :return: The org of this Consent.  # noqa: E501
        :rtype: Org
        """
        return self._org

    @org.setter
    def org(self, org):
        """Sets the org of this Consent.


        :param org: The org of this Consent.  # noqa: E501
        :type: Org
        """

        self._org = org

    @property
    def org_uid(self):
        """Gets the org_uid of this Consent.  # noqa: E501


        :return: The org_uid of this Consent.  # noqa: E501
        :rtype: str
        """
        return self._org_uid

    @org_uid.setter
    def org_uid(self, org_uid):
        """Sets the org_uid of this Consent.


        :param org_uid: The org_uid of this Consent.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and org_uid is None:
            raise ValueError("Invalid value for `org_uid`, must not be `None`")  # noqa: E501

        self._org_uid = org_uid

    @property
    def person(self):
        """Gets the person of this Consent.  # noqa: E501


        :return: The person of this Consent.  # noqa: E501
        :rtype: Person
        """
        return self._person

    @person.setter
    def person(self, person):
        """Sets the person of this Consent.


        :param person: The person of this Consent.  # noqa: E501
        :type: Person
        """

        self._person = person

    @property
    def person_uid(self):
        """Gets the person_uid of this Consent.  # noqa: E501


        :return: The person_uid of this Consent.  # noqa: E501
        :rtype: str
        """
        return self._person_uid

    @person_uid.setter
    def person_uid(self, person_uid):
        """Sets the person_uid of this Consent.


        :param person_uid: The person_uid of this Consent.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and person_uid is None:
            raise ValueError("Invalid value for `person_uid`, must not be `None`")  # noqa: E501

        self._person_uid = person_uid

    @property
    def process_code(self):
        """Gets the process_code of this Consent.  # noqa: E501


        :return: The process_code of this Consent.  # noqa: E501
        :rtype: str
        """
        return self._process_code

    @process_code.setter
    def process_code(self, process_code):
        """Sets the process_code of this Consent.


        :param process_code: The process_code of this Consent.  # noqa: E501
        :type: str
        """

        self._process_code = process_code

    @property
    def purpose(self):
        """Gets the purpose of this Consent.  # noqa: E501


        :return: The purpose of this Consent.  # noqa: E501
        :rtype: ConsentPurpose
        """
        return self._purpose

    @purpose.setter
    def purpose(self, purpose):
        """Sets the purpose of this Consent.


        :param purpose: The purpose of this Consent.  # noqa: E501
        :type: ConsentPurpose
        """
        if self._configuration.client_side_validation and purpose is None:
            raise ValueError("Invalid value for `purpose`, must not be `None`")  # noqa: E501

        self._purpose = purpose

    @property
    def scopes(self):
        """Gets the scopes of this Consent.  # noqa: E501


        :return: The scopes of this Consent.  # noqa: E501
        :rtype: list[str]
        """
        return self._scopes

    @scopes.setter
    def scopes(self, scopes):
        """Sets the scopes of this Consent.


        :param scopes: The scopes of this Consent.  # noqa: E501
        :type: list[str]
        """

        self._scopes = scopes

    @property
    def uid(self):
        """Gets the uid of this Consent.  # noqa: E501


        :return: The uid of this Consent.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this Consent.


        :param uid: The uid of this Consent.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and uid is None:
            raise ValueError("Invalid value for `uid`, must not be `None`")  # noqa: E501

        self._uid = uid

    @property
    def valid_from(self):
        """Gets the valid_from of this Consent.  # noqa: E501


        :return: The valid_from of this Consent.  # noqa: E501
        :rtype: datetime
        """
        return self._valid_from

    @valid_from.setter
    def valid_from(self, valid_from):
        """Sets the valid_from of this Consent.


        :param valid_from: The valid_from of this Consent.  # noqa: E501
        :type: datetime
        """
        if self._configuration.client_side_validation and valid_from is None:
            raise ValueError("Invalid value for `valid_from`, must not be `None`")  # noqa: E501

        self._valid_from = valid_from

    @property
    def valid_to(self):
        """Gets the valid_to of this Consent.  # noqa: E501


        :return: The valid_to of this Consent.  # noqa: E501
        :rtype: datetime
        """
        return self._valid_to

    @valid_to.setter
    def valid_to(self, valid_to):
        """Sets the valid_to of this Consent.


        :param valid_to: The valid_to of this Consent.  # noqa: E501
        :type: datetime
        """

        self._valid_to = valid_to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Consent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Consent):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Consent):
            return True

        return self.to_dict() != other.to_dict()
