# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class CountryWrite(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'iso2_code': 'str',
        'name_en': 'str',
        'name_native': 'str',
        'name_no': 'str'
    }

    attribute_map = {
        'iso2_code': 'iso2Code',
        'name_en': 'nameEn',
        'name_native': 'nameNative',
        'name_no': 'nameNo'
    }

    def __init__(self, iso2_code=None, name_en=None, name_native=None, name_no=None, _configuration=None):  # noqa: E501
        """CountryWrite - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._iso2_code = None
        self._name_en = None
        self._name_native = None
        self._name_no = None
        self.discriminator = None

        self.iso2_code = iso2_code
        self.name_en = name_en
        self.name_native = name_native
        self.name_no = name_no

    @property
    def iso2_code(self):
        """Gets the iso2_code of this CountryWrite.  # noqa: E501


        :return: The iso2_code of this CountryWrite.  # noqa: E501
        :rtype: str
        """
        return self._iso2_code

    @iso2_code.setter
    def iso2_code(self, iso2_code):
        """Sets the iso2_code of this CountryWrite.


        :param iso2_code: The iso2_code of this CountryWrite.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and iso2_code is None:
            raise ValueError("Invalid value for `iso2_code`, must not be `None`")  # noqa: E501

        self._iso2_code = iso2_code

    @property
    def name_en(self):
        """Gets the name_en of this CountryWrite.  # noqa: E501


        :return: The name_en of this CountryWrite.  # noqa: E501
        :rtype: str
        """
        return self._name_en

    @name_en.setter
    def name_en(self, name_en):
        """Sets the name_en of this CountryWrite.


        :param name_en: The name_en of this CountryWrite.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name_en is None:
            raise ValueError("Invalid value for `name_en`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name_en is not None and len(name_en) > 255):
            raise ValueError("Invalid value for `name_en`, length must be less than or equal to `255`")  # noqa: E501

        self._name_en = name_en

    @property
    def name_native(self):
        """Gets the name_native of this CountryWrite.  # noqa: E501


        :return: The name_native of this CountryWrite.  # noqa: E501
        :rtype: str
        """
        return self._name_native

    @name_native.setter
    def name_native(self, name_native):
        """Sets the name_native of this CountryWrite.


        :param name_native: The name_native of this CountryWrite.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name_native is None:
            raise ValueError("Invalid value for `name_native`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name_native is not None and len(name_native) > 255):
            raise ValueError("Invalid value for `name_native`, length must be less than or equal to `255`")  # noqa: E501

        self._name_native = name_native

    @property
    def name_no(self):
        """Gets the name_no of this CountryWrite.  # noqa: E501


        :return: The name_no of this CountryWrite.  # noqa: E501
        :rtype: str
        """
        return self._name_no

    @name_no.setter
    def name_no(self, name_no):
        """Sets the name_no of this CountryWrite.


        :param name_no: The name_no of this CountryWrite.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name_no is None:
            raise ValueError("Invalid value for `name_no`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name_no is not None and len(name_no) > 255):
            raise ValueError("Invalid value for `name_no`, length must be less than or equal to `255`")  # noqa: E501

        self._name_no = name_no

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CountryWrite, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CountryWrite):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CountryWrite):
            return True

        return self.to_dict() != other.to_dict()
