# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class GroupMember(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'group_uid': 'str',
        'last_changed_date': 'datetime',
        'person': 'Person',
        'person_uid': 'str',
        'uid': 'str'
    }

    attribute_map = {
        'group_uid': 'groupUid',
        'last_changed_date': 'lastChangedDate',
        'person': 'person',
        'person_uid': 'personUid',
        'uid': 'uid'
    }

    def __init__(self, group_uid=None, last_changed_date=None, person=None, person_uid=None, uid=None, _configuration=None):  # noqa: E501
        """GroupMember - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._group_uid = None
        self._last_changed_date = None
        self._person = None
        self._person_uid = None
        self._uid = None
        self.discriminator = None

        self.group_uid = group_uid
        if last_changed_date is not None:
            self.last_changed_date = last_changed_date
        if person is not None:
            self.person = person
        self.person_uid = person_uid
        self.uid = uid

    @property
    def group_uid(self):
        """Gets the group_uid of this GroupMember.  # noqa: E501


        :return: The group_uid of this GroupMember.  # noqa: E501
        :rtype: str
        """
        return self._group_uid

    @group_uid.setter
    def group_uid(self, group_uid):
        """Sets the group_uid of this GroupMember.


        :param group_uid: The group_uid of this GroupMember.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and group_uid is None:
            raise ValueError("Invalid value for `group_uid`, must not be `None`")  # noqa: E501

        self._group_uid = group_uid

    @property
    def last_changed_date(self):
        """Gets the last_changed_date of this GroupMember.  # noqa: E501


        :return: The last_changed_date of this GroupMember.  # noqa: E501
        :rtype: datetime
        """
        return self._last_changed_date

    @last_changed_date.setter
    def last_changed_date(self, last_changed_date):
        """Sets the last_changed_date of this GroupMember.


        :param last_changed_date: The last_changed_date of this GroupMember.  # noqa: E501
        :type: datetime
        """

        self._last_changed_date = last_changed_date

    @property
    def person(self):
        """Gets the person of this GroupMember.  # noqa: E501


        :return: The person of this GroupMember.  # noqa: E501
        :rtype: Person
        """
        return self._person

    @person.setter
    def person(self, person):
        """Sets the person of this GroupMember.


        :param person: The person of this GroupMember.  # noqa: E501
        :type: Person
        """

        self._person = person

    @property
    def person_uid(self):
        """Gets the person_uid of this GroupMember.  # noqa: E501


        :return: The person_uid of this GroupMember.  # noqa: E501
        :rtype: str
        """
        return self._person_uid

    @person_uid.setter
    def person_uid(self, person_uid):
        """Sets the person_uid of this GroupMember.


        :param person_uid: The person_uid of this GroupMember.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and person_uid is None:
            raise ValueError("Invalid value for `person_uid`, must not be `None`")  # noqa: E501

        self._person_uid = person_uid

    @property
    def uid(self):
        """Gets the uid of this GroupMember.  # noqa: E501


        :return: The uid of this GroupMember.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this GroupMember.


        :param uid: The uid of this GroupMember.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and uid is None:
            raise ValueError("Invalid value for `uid`, must not be `None`")  # noqa: E501

        self._uid = uid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupMember, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupMember):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GroupMember):
            return True

        return self.to_dict() != other.to_dict()
