# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class GroupMemberWrite(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'person_uid': 'str'
    }

    attribute_map = {
        'person_uid': 'personUid'
    }

    def __init__(self, person_uid=None, _configuration=None):  # noqa: E501
        """GroupMemberWrite - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._person_uid = None
        self.discriminator = None

        self.person_uid = person_uid

    @property
    def person_uid(self):
        """Gets the person_uid of this GroupMemberWrite.  # noqa: E501


        :return: The person_uid of this GroupMemberWrite.  # noqa: E501
        :rtype: str
        """
        return self._person_uid

    @person_uid.setter
    def person_uid(self, person_uid):
        """Sets the person_uid of this GroupMemberWrite.


        :param person_uid: The person_uid of this GroupMemberWrite.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and person_uid is None:
            raise ValueError("Invalid value for `person_uid`, must not be `None`")  # noqa: E501

        self._person_uid = person_uid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupMemberWrite, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupMemberWrite):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GroupMemberWrite):
            return True

        return self.to_dict() != other.to_dict()
