# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Group(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'app_uid': 'str',
        'last_changed_date': 'datetime',
        'name': 'str',
        'org_uid': 'str',
        'rule': 'str',
        'tags': 'list[str]',
        'type': 'GroupType',
        'uid': 'str'
    }

    attribute_map = {
        'app_uid': 'appUid',
        'last_changed_date': 'lastChangedDate',
        'name': 'name',
        'org_uid': 'orgUid',
        'rule': 'rule',
        'tags': 'tags',
        'type': 'type',
        'uid': 'uid'
    }

    def __init__(self, app_uid=None, last_changed_date=None, name=None, org_uid=None, rule=None, tags=None, type=None, uid=None, _configuration=None):  # noqa: E501
        """Group - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._app_uid = None
        self._last_changed_date = None
        self._name = None
        self._org_uid = None
        self._rule = None
        self._tags = None
        self._type = None
        self._uid = None
        self.discriminator = None

        self.app_uid = app_uid
        self.last_changed_date = last_changed_date
        self.name = name
        if org_uid is not None:
            self.org_uid = org_uid
        if rule is not None:
            self.rule = rule
        if tags is not None:
            self.tags = tags
        self.type = type
        self.uid = uid

    @property
    def app_uid(self):
        """Gets the app_uid of this Group.  # noqa: E501


        :return: The app_uid of this Group.  # noqa: E501
        :rtype: str
        """
        return self._app_uid

    @app_uid.setter
    def app_uid(self, app_uid):
        """Sets the app_uid of this Group.


        :param app_uid: The app_uid of this Group.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and app_uid is None:
            raise ValueError("Invalid value for `app_uid`, must not be `None`")  # noqa: E501

        self._app_uid = app_uid

    @property
    def last_changed_date(self):
        """Gets the last_changed_date of this Group.  # noqa: E501


        :return: The last_changed_date of this Group.  # noqa: E501
        :rtype: datetime
        """
        return self._last_changed_date

    @last_changed_date.setter
    def last_changed_date(self, last_changed_date):
        """Sets the last_changed_date of this Group.


        :param last_changed_date: The last_changed_date of this Group.  # noqa: E501
        :type: datetime
        """
        if self._configuration.client_side_validation and last_changed_date is None:
            raise ValueError("Invalid value for `last_changed_date`, must not be `None`")  # noqa: E501

        self._last_changed_date = last_changed_date

    @property
    def name(self):
        """Gets the name of this Group.  # noqa: E501


        :return: The name of this Group.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Group.


        :param name: The name of this Group.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def org_uid(self):
        """Gets the org_uid of this Group.  # noqa: E501


        :return: The org_uid of this Group.  # noqa: E501
        :rtype: str
        """
        return self._org_uid

    @org_uid.setter
    def org_uid(self, org_uid):
        """Sets the org_uid of this Group.


        :param org_uid: The org_uid of this Group.  # noqa: E501
        :type: str
        """

        self._org_uid = org_uid

    @property
    def rule(self):
        """Gets the rule of this Group.  # noqa: E501


        :return: The rule of this Group.  # noqa: E501
        :rtype: str
        """
        return self._rule

    @rule.setter
    def rule(self, rule):
        """Sets the rule of this Group.


        :param rule: The rule of this Group.  # noqa: E501
        :type: str
        """

        self._rule = rule

    @property
    def tags(self):
        """Gets the tags of this Group.  # noqa: E501


        :return: The tags of this Group.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this Group.


        :param tags: The tags of this Group.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def type(self):
        """Gets the type of this Group.  # noqa: E501


        :return: The type of this Group.  # noqa: E501
        :rtype: GroupType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Group.


        :param type: The type of this Group.  # noqa: E501
        :type: GroupType
        """
        if self._configuration.client_side_validation and type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def uid(self):
        """Gets the uid of this Group.  # noqa: E501


        :return: The uid of this Group.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this Group.


        :param uid: The uid of this Group.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and uid is None:
            raise ValueError("Invalid value for `uid`, must not be `None`")  # noqa: E501

        self._uid = uid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Group, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Group):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Group):
            return True

        return self.to_dict() != other.to_dict()
