# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class OrgWrite(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'active_status': 'OrgActiveStatus',
        'billing_address': 'Address',
        'district_name': 'str',
        'name': 'str',
        'postal_address': 'Address',
        'type': 'OrgActiveStatus',
        'visiting_address': 'Address'
    }

    attribute_map = {
        'active_status': 'activeStatus',
        'billing_address': 'billingAddress',
        'district_name': 'districtName',
        'name': 'name',
        'postal_address': 'postalAddress',
        'type': 'type',
        'visiting_address': 'visitingAddress'
    }

    def __init__(self, active_status=None, billing_address=None, district_name=None, name=None, postal_address=None, type=None, visiting_address=None, _configuration=None):  # noqa: E501
        """OrgWrite - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._active_status = None
        self._billing_address = None
        self._district_name = None
        self._name = None
        self._postal_address = None
        self._type = None
        self._visiting_address = None
        self.discriminator = None

        self.active_status = active_status
        if billing_address is not None:
            self.billing_address = billing_address
        self.district_name = district_name
        self.name = name
        if postal_address is not None:
            self.postal_address = postal_address
        self.type = type
        if visiting_address is not None:
            self.visiting_address = visiting_address

    @property
    def active_status(self):
        """Gets the active_status of this OrgWrite.  # noqa: E501


        :return: The active_status of this OrgWrite.  # noqa: E501
        :rtype: OrgActiveStatus
        """
        return self._active_status

    @active_status.setter
    def active_status(self, active_status):
        """Sets the active_status of this OrgWrite.


        :param active_status: The active_status of this OrgWrite.  # noqa: E501
        :type: OrgActiveStatus
        """
        if self._configuration.client_side_validation and active_status is None:
            raise ValueError("Invalid value for `active_status`, must not be `None`")  # noqa: E501

        self._active_status = active_status

    @property
    def billing_address(self):
        """Gets the billing_address of this OrgWrite.  # noqa: E501


        :return: The billing_address of this OrgWrite.  # noqa: E501
        :rtype: Address
        """
        return self._billing_address

    @billing_address.setter
    def billing_address(self, billing_address):
        """Sets the billing_address of this OrgWrite.


        :param billing_address: The billing_address of this OrgWrite.  # noqa: E501
        :type: Address
        """

        self._billing_address = billing_address

    @property
    def district_name(self):
        """Gets the district_name of this OrgWrite.  # noqa: E501


        :return: The district_name of this OrgWrite.  # noqa: E501
        :rtype: str
        """
        return self._district_name

    @district_name.setter
    def district_name(self, district_name):
        """Sets the district_name of this OrgWrite.


        :param district_name: The district_name of this OrgWrite.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and district_name is None:
            raise ValueError("Invalid value for `district_name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                district_name is not None and len(district_name) > 255):
            raise ValueError("Invalid value for `district_name`, length must be less than or equal to `255`")  # noqa: E501

        self._district_name = district_name

    @property
    def name(self):
        """Gets the name of this OrgWrite.  # noqa: E501


        :return: The name of this OrgWrite.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OrgWrite.


        :param name: The name of this OrgWrite.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) > 255):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501

        self._name = name

    @property
    def postal_address(self):
        """Gets the postal_address of this OrgWrite.  # noqa: E501


        :return: The postal_address of this OrgWrite.  # noqa: E501
        :rtype: Address
        """
        return self._postal_address

    @postal_address.setter
    def postal_address(self, postal_address):
        """Sets the postal_address of this OrgWrite.


        :param postal_address: The postal_address of this OrgWrite.  # noqa: E501
        :type: Address
        """

        self._postal_address = postal_address

    @property
    def type(self):
        """Gets the type of this OrgWrite.  # noqa: E501


        :return: The type of this OrgWrite.  # noqa: E501
        :rtype: OrgActiveStatus
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this OrgWrite.


        :param type: The type of this OrgWrite.  # noqa: E501
        :type: OrgActiveStatus
        """
        if self._configuration.client_side_validation and type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def visiting_address(self):
        """Gets the visiting_address of this OrgWrite.  # noqa: E501


        :return: The visiting_address of this OrgWrite.  # noqa: E501
        :rtype: Address
        """
        return self._visiting_address

    @visiting_address.setter
    def visiting_address(self, visiting_address):
        """Sets the visiting_address of this OrgWrite.


        :param visiting_address: The visiting_address of this OrgWrite.  # noqa: E501
        :type: Address
        """

        self._visiting_address = visiting_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgWrite, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgWrite):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrgWrite):
            return True

        return self.to_dict() != other.to_dict()
