# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class PersonRelation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'grant_to_origin': 'PersonRelationGrantToOrigin',
        'grant_to_target': 'PersonRelationGrantToTarget',
        'target': 'Person',
        'target_uid': 'str',
        'type': 'PersonRelationType',
        'valid_from': 'datetime',
        'valid_to': 'datetime'
    }

    attribute_map = {
        'grant_to_origin': 'grantToOrigin',
        'grant_to_target': 'grantToTarget',
        'target': 'target',
        'target_uid': 'targetUid',
        'type': 'type',
        'valid_from': 'validFrom',
        'valid_to': 'validTo'
    }

    def __init__(self, grant_to_origin=None, grant_to_target=None, target=None, target_uid=None, type=None, valid_from=None, valid_to=None, _configuration=None):  # noqa: E501
        """PersonRelation - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._grant_to_origin = None
        self._grant_to_target = None
        self._target = None
        self._target_uid = None
        self._type = None
        self._valid_from = None
        self._valid_to = None
        self.discriminator = None

        self.grant_to_origin = grant_to_origin
        self.grant_to_target = grant_to_target
        if target is not None:
            self.target = target
        self.target_uid = target_uid
        self.type = type
        self.valid_from = valid_from
        if valid_to is not None:
            self.valid_to = valid_to

    @property
    def grant_to_origin(self):
        """Gets the grant_to_origin of this PersonRelation.  # noqa: E501


        :return: The grant_to_origin of this PersonRelation.  # noqa: E501
        :rtype: PersonRelationGrantToOrigin
        """
        return self._grant_to_origin

    @grant_to_origin.setter
    def grant_to_origin(self, grant_to_origin):
        """Sets the grant_to_origin of this PersonRelation.


        :param grant_to_origin: The grant_to_origin of this PersonRelation.  # noqa: E501
        :type: PersonRelationGrantToOrigin
        """
        if self._configuration.client_side_validation and grant_to_origin is None:
            raise ValueError("Invalid value for `grant_to_origin`, must not be `None`")  # noqa: E501

        self._grant_to_origin = grant_to_origin

    @property
    def grant_to_target(self):
        """Gets the grant_to_target of this PersonRelation.  # noqa: E501


        :return: The grant_to_target of this PersonRelation.  # noqa: E501
        :rtype: PersonRelationGrantToTarget
        """
        return self._grant_to_target

    @grant_to_target.setter
    def grant_to_target(self, grant_to_target):
        """Sets the grant_to_target of this PersonRelation.


        :param grant_to_target: The grant_to_target of this PersonRelation.  # noqa: E501
        :type: PersonRelationGrantToTarget
        """
        if self._configuration.client_side_validation and grant_to_target is None:
            raise ValueError("Invalid value for `grant_to_target`, must not be `None`")  # noqa: E501

        self._grant_to_target = grant_to_target

    @property
    def target(self):
        """Gets the target of this PersonRelation.  # noqa: E501


        :return: The target of this PersonRelation.  # noqa: E501
        :rtype: Person
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this PersonRelation.


        :param target: The target of this PersonRelation.  # noqa: E501
        :type: Person
        """

        self._target = target

    @property
    def target_uid(self):
        """Gets the target_uid of this PersonRelation.  # noqa: E501


        :return: The target_uid of this PersonRelation.  # noqa: E501
        :rtype: str
        """
        return self._target_uid

    @target_uid.setter
    def target_uid(self, target_uid):
        """Sets the target_uid of this PersonRelation.


        :param target_uid: The target_uid of this PersonRelation.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and target_uid is None:
            raise ValueError("Invalid value for `target_uid`, must not be `None`")  # noqa: E501

        self._target_uid = target_uid

    @property
    def type(self):
        """Gets the type of this PersonRelation.  # noqa: E501


        :return: The type of this PersonRelation.  # noqa: E501
        :rtype: PersonRelationType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PersonRelation.


        :param type: The type of this PersonRelation.  # noqa: E501
        :type: PersonRelationType
        """
        if self._configuration.client_side_validation and type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def valid_from(self):
        """Gets the valid_from of this PersonRelation.  # noqa: E501


        :return: The valid_from of this PersonRelation.  # noqa: E501
        :rtype: datetime
        """
        return self._valid_from

    @valid_from.setter
    def valid_from(self, valid_from):
        """Sets the valid_from of this PersonRelation.


        :param valid_from: The valid_from of this PersonRelation.  # noqa: E501
        :type: datetime
        """
        if self._configuration.client_side_validation and valid_from is None:
            raise ValueError("Invalid value for `valid_from`, must not be `None`")  # noqa: E501

        self._valid_from = valid_from

    @property
    def valid_to(self):
        """Gets the valid_to of this PersonRelation.  # noqa: E501


        :return: The valid_to of this PersonRelation.  # noqa: E501
        :rtype: datetime
        """
        return self._valid_to

    @valid_to.setter
    def valid_to(self, valid_to):
        """Sets the valid_to of this PersonRelation.


        :param valid_to: The valid_to of this PersonRelation.  # noqa: E501
        :type: datetime
        """

        self._valid_to = valid_to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PersonRelation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PersonRelation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PersonRelation):
            return True

        return self.to_dict() != other.to_dict()
