# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Person(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'Address',
        'affiliations': 'list[Affiliation]',
        'birth_date': 'date',
        'cell_phone': 'str',
        'cell_phone_verified': 'bool',
        'church': 'Org',
        'church_uid': 'str',
        'consents': 'list[Consent]',
        'deceased_date': 'date',
        'display_name': 'str',
        'email': 'str',
        'email_verified': 'bool',
        'first_name': 'str',
        'gender': 'Gender',
        'home_phone': 'str',
        'is_active': 'bool',
        'last_changed_date': 'datetime',
        'last_name': 'str',
        'marital_status': 'MaritalStatus',
        'middle_name': 'str',
        'national_ids': 'list[NationalId]',
        'person_id': 'int',
        'preferences': 'Preferences',
        'profile_picture': 'str',
        'relations': 'list[PersonRelation]',
        'role_assignments': 'list[RoleAssignment]',
        'static_group_memberships': 'list[GroupMember]',
        'uid': 'str'
    }

    attribute_map = {
        'address': 'address',
        'affiliations': 'affiliations',
        'birth_date': 'birthDate',
        'cell_phone': 'cellPhone',
        'cell_phone_verified': 'cellPhoneVerified',
        'church': 'church',
        'church_uid': 'churchUid',
        'consents': 'consents',
        'deceased_date': 'deceasedDate',
        'display_name': 'displayName',
        'email': 'email',
        'email_verified': 'emailVerified',
        'first_name': 'firstName',
        'gender': 'gender',
        'home_phone': 'homePhone',
        'is_active': 'isActive',
        'last_changed_date': 'lastChangedDate',
        'last_name': 'lastName',
        'marital_status': 'maritalStatus',
        'middle_name': 'middleName',
        'national_ids': 'nationalIds',
        'person_id': 'personID',
        'preferences': 'preferences',
        'profile_picture': 'profilePicture',
        'relations': 'relations',
        'role_assignments': 'roleAssignments',
        'static_group_memberships': 'staticGroupMemberships',
        'uid': 'uid'
    }

    def __init__(self, address=None, affiliations=None, birth_date=None, cell_phone=None, cell_phone_verified=None, church=None, church_uid=None, consents=None, deceased_date=None, display_name=None, email=None, email_verified=None, first_name=None, gender=None, home_phone=None, is_active=None, last_changed_date=None, last_name=None, marital_status=None, middle_name=None, national_ids=None, person_id=None, preferences=None, profile_picture=None, relations=None, role_assignments=None, static_group_memberships=None, uid=None, _configuration=None):  # noqa: E501
        """Person - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._address = None
        self._affiliations = None
        self._birth_date = None
        self._cell_phone = None
        self._cell_phone_verified = None
        self._church = None
        self._church_uid = None
        self._consents = None
        self._deceased_date = None
        self._display_name = None
        self._email = None
        self._email_verified = None
        self._first_name = None
        self._gender = None
        self._home_phone = None
        self._is_active = None
        self._last_changed_date = None
        self._last_name = None
        self._marital_status = None
        self._middle_name = None
        self._national_ids = None
        self._person_id = None
        self._preferences = None
        self._profile_picture = None
        self._relations = None
        self._role_assignments = None
        self._static_group_memberships = None
        self._uid = None
        self.discriminator = None

        if address is not None:
            self.address = address
        if affiliations is not None:
            self.affiliations = affiliations
        self.birth_date = birth_date
        if cell_phone is not None:
            self.cell_phone = cell_phone
        if cell_phone_verified is not None:
            self.cell_phone_verified = cell_phone_verified
        if church is not None:
            self.church = church
        if church_uid is not None:
            self.church_uid = church_uid
        if consents is not None:
            self.consents = consents
        if deceased_date is not None:
            self.deceased_date = deceased_date
        self.display_name = display_name
        if email is not None:
            self.email = email
        if email_verified is not None:
            self.email_verified = email_verified
        self.first_name = first_name
        self.gender = gender
        if home_phone is not None:
            self.home_phone = home_phone
        if is_active is not None:
            self.is_active = is_active
        self.last_changed_date = last_changed_date
        self.last_name = last_name
        self.marital_status = marital_status
        if middle_name is not None:
            self.middle_name = middle_name
        if national_ids is not None:
            self.national_ids = national_ids
        self.person_id = person_id
        if preferences is not None:
            self.preferences = preferences
        if profile_picture is not None:
            self.profile_picture = profile_picture
        if relations is not None:
            self.relations = relations
        if role_assignments is not None:
            self.role_assignments = role_assignments
        if static_group_memberships is not None:
            self.static_group_memberships = static_group_memberships
        self.uid = uid

    @property
    def address(self):
        """Gets the address of this Person.  # noqa: E501


        :return: The address of this Person.  # noqa: E501
        :rtype: Address
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this Person.


        :param address: The address of this Person.  # noqa: E501
        :type: Address
        """

        self._address = address

    @property
    def affiliations(self):
        """Gets the affiliations of this Person.  # noqa: E501


        :return: The affiliations of this Person.  # noqa: E501
        :rtype: list[Affiliation]
        """
        return self._affiliations

    @affiliations.setter
    def affiliations(self, affiliations):
        """Sets the affiliations of this Person.


        :param affiliations: The affiliations of this Person.  # noqa: E501
        :type: list[Affiliation]
        """

        self._affiliations = affiliations

    @property
    def birth_date(self):
        """Gets the birth_date of this Person.  # noqa: E501


        :return: The birth_date of this Person.  # noqa: E501
        :rtype: date
        """
        return self._birth_date

    @birth_date.setter
    def birth_date(self, birth_date):
        """Sets the birth_date of this Person.


        :param birth_date: The birth_date of this Person.  # noqa: E501
        :type: date
        """
        if self._configuration.client_side_validation and birth_date is None:
            raise ValueError("Invalid value for `birth_date`, must not be `None`")  # noqa: E501

        self._birth_date = birth_date

    @property
    def cell_phone(self):
        """Gets the cell_phone of this Person.  # noqa: E501


        :return: The cell_phone of this Person.  # noqa: E501
        :rtype: str
        """
        return self._cell_phone

    @cell_phone.setter
    def cell_phone(self, cell_phone):
        """Sets the cell_phone of this Person.


        :param cell_phone: The cell_phone of this Person.  # noqa: E501
        :type: str
        """

        self._cell_phone = cell_phone

    @property
    def cell_phone_verified(self):
        """Gets the cell_phone_verified of this Person.  # noqa: E501


        :return: The cell_phone_verified of this Person.  # noqa: E501
        :rtype: bool
        """
        return self._cell_phone_verified

    @cell_phone_verified.setter
    def cell_phone_verified(self, cell_phone_verified):
        """Sets the cell_phone_verified of this Person.


        :param cell_phone_verified: The cell_phone_verified of this Person.  # noqa: E501
        :type: bool
        """

        self._cell_phone_verified = cell_phone_verified

    @property
    def church(self):
        """Gets the church of this Person.  # noqa: E501


        :return: The church of this Person.  # noqa: E501
        :rtype: Org
        """
        return self._church

    @church.setter
    def church(self, church):
        """Sets the church of this Person.


        :param church: The church of this Person.  # noqa: E501
        :type: Org
        """

        self._church = church

    @property
    def church_uid(self):
        """Gets the church_uid of this Person.  # noqa: E501


        :return: The church_uid of this Person.  # noqa: E501
        :rtype: str
        """
        return self._church_uid

    @church_uid.setter
    def church_uid(self, church_uid):
        """Sets the church_uid of this Person.


        :param church_uid: The church_uid of this Person.  # noqa: E501
        :type: str
        """

        self._church_uid = church_uid

    @property
    def consents(self):
        """Gets the consents of this Person.  # noqa: E501


        :return: The consents of this Person.  # noqa: E501
        :rtype: list[Consent]
        """
        return self._consents

    @consents.setter
    def consents(self, consents):
        """Sets the consents of this Person.


        :param consents: The consents of this Person.  # noqa: E501
        :type: list[Consent]
        """

        self._consents = consents

    @property
    def deceased_date(self):
        """Gets the deceased_date of this Person.  # noqa: E501


        :return: The deceased_date of this Person.  # noqa: E501
        :rtype: date
        """
        return self._deceased_date

    @deceased_date.setter
    def deceased_date(self, deceased_date):
        """Sets the deceased_date of this Person.


        :param deceased_date: The deceased_date of this Person.  # noqa: E501
        :type: date
        """

        self._deceased_date = deceased_date

    @property
    def display_name(self):
        """Gets the display_name of this Person.  # noqa: E501


        :return: The display_name of this Person.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this Person.


        :param display_name: The display_name of this Person.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                display_name is not None and len(display_name) > 255):
            raise ValueError("Invalid value for `display_name`, length must be less than or equal to `255`")  # noqa: E501

        self._display_name = display_name

    @property
    def email(self):
        """Gets the email of this Person.  # noqa: E501


        :return: The email of this Person.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Person.


        :param email: The email of this Person.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def email_verified(self):
        """Gets the email_verified of this Person.  # noqa: E501


        :return: The email_verified of this Person.  # noqa: E501
        :rtype: bool
        """
        return self._email_verified

    @email_verified.setter
    def email_verified(self, email_verified):
        """Sets the email_verified of this Person.


        :param email_verified: The email_verified of this Person.  # noqa: E501
        :type: bool
        """

        self._email_verified = email_verified

    @property
    def first_name(self):
        """Gets the first_name of this Person.  # noqa: E501


        :return: The first_name of this Person.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this Person.


        :param first_name: The first_name of this Person.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                first_name is not None and len(first_name) > 255):
            raise ValueError("Invalid value for `first_name`, length must be less than or equal to `255`")  # noqa: E501

        self._first_name = first_name

    @property
    def gender(self):
        """Gets the gender of this Person.  # noqa: E501


        :return: The gender of this Person.  # noqa: E501
        :rtype: Gender
        """
        return self._gender

    @gender.setter
    def gender(self, gender):
        """Sets the gender of this Person.


        :param gender: The gender of this Person.  # noqa: E501
        :type: Gender
        """
        if self._configuration.client_side_validation and gender is None:
            raise ValueError("Invalid value for `gender`, must not be `None`")  # noqa: E501

        self._gender = gender

    @property
    def home_phone(self):
        """Gets the home_phone of this Person.  # noqa: E501


        :return: The home_phone of this Person.  # noqa: E501
        :rtype: str
        """
        return self._home_phone

    @home_phone.setter
    def home_phone(self, home_phone):
        """Sets the home_phone of this Person.


        :param home_phone: The home_phone of this Person.  # noqa: E501
        :type: str
        """

        self._home_phone = home_phone

    @property
    def is_active(self):
        """Gets the is_active of this Person.  # noqa: E501


        :return: The is_active of this Person.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this Person.


        :param is_active: The is_active of this Person.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    @property
    def last_changed_date(self):
        """Gets the last_changed_date of this Person.  # noqa: E501


        :return: The last_changed_date of this Person.  # noqa: E501
        :rtype: datetime
        """
        return self._last_changed_date

    @last_changed_date.setter
    def last_changed_date(self, last_changed_date):
        """Sets the last_changed_date of this Person.


        :param last_changed_date: The last_changed_date of this Person.  # noqa: E501
        :type: datetime
        """
        if self._configuration.client_side_validation and last_changed_date is None:
            raise ValueError("Invalid value for `last_changed_date`, must not be `None`")  # noqa: E501

        self._last_changed_date = last_changed_date

    @property
    def last_name(self):
        """Gets the last_name of this Person.  # noqa: E501


        :return: The last_name of this Person.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this Person.


        :param last_name: The last_name of this Person.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                last_name is not None and len(last_name) > 255):
            raise ValueError("Invalid value for `last_name`, length must be less than or equal to `255`")  # noqa: E501

        self._last_name = last_name

    @property
    def marital_status(self):
        """Gets the marital_status of this Person.  # noqa: E501


        :return: The marital_status of this Person.  # noqa: E501
        :rtype: MaritalStatus
        """
        return self._marital_status

    @marital_status.setter
    def marital_status(self, marital_status):
        """Sets the marital_status of this Person.


        :param marital_status: The marital_status of this Person.  # noqa: E501
        :type: MaritalStatus
        """
        if self._configuration.client_side_validation and marital_status is None:
            raise ValueError("Invalid value for `marital_status`, must not be `None`")  # noqa: E501

        self._marital_status = marital_status

    @property
    def middle_name(self):
        """Gets the middle_name of this Person.  # noqa: E501


        :return: The middle_name of this Person.  # noqa: E501
        :rtype: str
        """
        return self._middle_name

    @middle_name.setter
    def middle_name(self, middle_name):
        """Sets the middle_name of this Person.


        :param middle_name: The middle_name of this Person.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                middle_name is not None and len(middle_name) > 255):
            raise ValueError("Invalid value for `middle_name`, length must be less than or equal to `255`")  # noqa: E501

        self._middle_name = middle_name

    @property
    def national_ids(self):
        """Gets the national_ids of this Person.  # noqa: E501


        :return: The national_ids of this Person.  # noqa: E501
        :rtype: list[NationalId]
        """
        return self._national_ids

    @national_ids.setter
    def national_ids(self, national_ids):
        """Sets the national_ids of this Person.


        :param national_ids: The national_ids of this Person.  # noqa: E501
        :type: list[NationalId]
        """

        self._national_ids = national_ids

    @property
    def person_id(self):
        """Gets the person_id of this Person.  # noqa: E501


        :return: The person_id of this Person.  # noqa: E501
        :rtype: int
        """
        return self._person_id

    @person_id.setter
    def person_id(self, person_id):
        """Sets the person_id of this Person.


        :param person_id: The person_id of this Person.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and person_id is None:
            raise ValueError("Invalid value for `person_id`, must not be `None`")  # noqa: E501

        self._person_id = person_id

    @property
    def preferences(self):
        """Gets the preferences of this Person.  # noqa: E501


        :return: The preferences of this Person.  # noqa: E501
        :rtype: Preferences
        """
        return self._preferences

    @preferences.setter
    def preferences(self, preferences):
        """Sets the preferences of this Person.


        :param preferences: The preferences of this Person.  # noqa: E501
        :type: Preferences
        """

        self._preferences = preferences

    @property
    def profile_picture(self):
        """Gets the profile_picture of this Person.  # noqa: E501

        URL of person's profile picture  # noqa: E501

        :return: The profile_picture of this Person.  # noqa: E501
        :rtype: str
        """
        return self._profile_picture

    @profile_picture.setter
    def profile_picture(self, profile_picture):
        """Sets the profile_picture of this Person.

        URL of person's profile picture  # noqa: E501

        :param profile_picture: The profile_picture of this Person.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                profile_picture is not None and len(profile_picture) > 512):
            raise ValueError("Invalid value for `profile_picture`, length must be less than or equal to `512`")  # noqa: E501

        self._profile_picture = profile_picture

    @property
    def relations(self):
        """Gets the relations of this Person.  # noqa: E501


        :return: The relations of this Person.  # noqa: E501
        :rtype: list[PersonRelation]
        """
        return self._relations

    @relations.setter
    def relations(self, relations):
        """Sets the relations of this Person.


        :param relations: The relations of this Person.  # noqa: E501
        :type: list[PersonRelation]
        """

        self._relations = relations

    @property
    def role_assignments(self):
        """Gets the role_assignments of this Person.  # noqa: E501


        :return: The role_assignments of this Person.  # noqa: E501
        :rtype: list[RoleAssignment]
        """
        return self._role_assignments

    @role_assignments.setter
    def role_assignments(self, role_assignments):
        """Sets the role_assignments of this Person.


        :param role_assignments: The role_assignments of this Person.  # noqa: E501
        :type: list[RoleAssignment]
        """

        self._role_assignments = role_assignments

    @property
    def static_group_memberships(self):
        """Gets the static_group_memberships of this Person.  # noqa: E501


        :return: The static_group_memberships of this Person.  # noqa: E501
        :rtype: list[GroupMember]
        """
        return self._static_group_memberships

    @static_group_memberships.setter
    def static_group_memberships(self, static_group_memberships):
        """Sets the static_group_memberships of this Person.


        :param static_group_memberships: The static_group_memberships of this Person.  # noqa: E501
        :type: list[GroupMember]
        """

        self._static_group_memberships = static_group_memberships

    @property
    def uid(self):
        """Gets the uid of this Person.  # noqa: E501


        :return: The uid of this Person.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this Person.


        :param uid: The uid of this Person.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and uid is None:
            raise ValueError("Invalid value for `uid`, must not be `None`")  # noqa: E501

        self._uid = uid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Person, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Person):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Person):
            return True

        return self.to_dict() != other.to_dict()
