# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Preferences(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content_languages': 'list[str]',
        'ui_languages': 'list[str]',
        'visibility': 'VisibilityPreferences'
    }

    attribute_map = {
        'content_languages': 'contentLanguages',
        'ui_languages': 'uiLanguages',
        'visibility': 'visibility'
    }

    def __init__(self, content_languages=None, ui_languages=None, visibility=None, _configuration=None):  # noqa: E501
        """Preferences - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._content_languages = None
        self._ui_languages = None
        self._visibility = None
        self.discriminator = None

        if content_languages is not None:
            self.content_languages = content_languages
        if ui_languages is not None:
            self.ui_languages = ui_languages
        if visibility is not None:
            self.visibility = visibility

    @property
    def content_languages(self):
        """Gets the content_languages of this Preferences.  # noqa: E501


        :return: The content_languages of this Preferences.  # noqa: E501
        :rtype: list[str]
        """
        return self._content_languages

    @content_languages.setter
    def content_languages(self, content_languages):
        """Sets the content_languages of this Preferences.


        :param content_languages: The content_languages of this Preferences.  # noqa: E501
        :type: list[str]
        """

        self._content_languages = content_languages

    @property
    def ui_languages(self):
        """Gets the ui_languages of this Preferences.  # noqa: E501


        :return: The ui_languages of this Preferences.  # noqa: E501
        :rtype: list[str]
        """
        return self._ui_languages

    @ui_languages.setter
    def ui_languages(self, ui_languages):
        """Sets the ui_languages of this Preferences.


        :param ui_languages: The ui_languages of this Preferences.  # noqa: E501
        :type: list[str]
        """

        self._ui_languages = ui_languages

    @property
    def visibility(self):
        """Gets the visibility of this Preferences.  # noqa: E501


        :return: The visibility of this Preferences.  # noqa: E501
        :rtype: VisibilityPreferences
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility):
        """Sets the visibility of this Preferences.


        :param visibility: The visibility of this Preferences.  # noqa: E501
        :type: VisibilityPreferences
        """

        self._visibility = visibility

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Preferences, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Preferences):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Preferences):
            return True

        return self.to_dict() != other.to_dict()
