# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class VisibilityPreferences(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'birthday_list': 'bool',
        'search': 'SearchVisibility'
    }

    attribute_map = {
        'birthday_list': 'birthdayList',
        'search': 'search'
    }

    def __init__(self, birthday_list=None, search=None, _configuration=None):  # noqa: E501
        """VisibilityPreferences - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._birthday_list = None
        self._search = None
        self.discriminator = None

        if birthday_list is not None:
            self.birthday_list = birthday_list
        self.search = search

    @property
    def birthday_list(self):
        """Gets the birthday_list of this VisibilityPreferences.  # noqa: E501


        :return: The birthday_list of this VisibilityPreferences.  # noqa: E501
        :rtype: bool
        """
        return self._birthday_list

    @birthday_list.setter
    def birthday_list(self, birthday_list):
        """Sets the birthday_list of this VisibilityPreferences.


        :param birthday_list: The birthday_list of this VisibilityPreferences.  # noqa: E501
        :type: bool
        """

        self._birthday_list = birthday_list

    @property
    def search(self):
        """Gets the search of this VisibilityPreferences.  # noqa: E501


        :return: The search of this VisibilityPreferences.  # noqa: E501
        :rtype: SearchVisibility
        """
        return self._search

    @search.setter
    def search(self, search):
        """Sets the search of this VisibilityPreferences.


        :param search: The search of this VisibilityPreferences.  # noqa: E501
        :type: SearchVisibility
        """
        if self._configuration.client_side_validation and search is None:
            raise ValueError("Invalid value for `search`, must not be `None`")  # noqa: E501

        self._search = search

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VisibilityPreferences, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VisibilityPreferences):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VisibilityPreferences):
            return True

        return self.to_dict() != other.to_dict()
