# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.relations_api import RelationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRelationsApi(unittest.TestCase):
    """RelationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.relations_api.RelationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_relation(self):
        """Test case for create_relation

        Create relation  # noqa: E501
        """
        pass

    def test_find_relations(self):
        """Test case for find_relations

        Find relations  # noqa: E501
        """
        pass

    def test_get_relation(self):
        """Test case for get_relation

        Get relation  # noqa: E501
        """
        pass

    def test_update_relation(self):
        """Test case for update_relation

        Update relation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
