# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.group_members_api import GroupMembersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGroupMembersApi(unittest.TestCase):
    """GroupMembersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.group_members_api.GroupMembersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_group_member(self):
        """Test case for create_group_member

        Create a group member  # noqa: E501
        """
        pass

    def test_find_group_members(self):
        """Test case for find_group_members

        Find a group member  # noqa: E501
        """
        pass

    def test_get_group_member(self):
        """Test case for get_group_member

        Get group members  # noqa: E501
        """
        pass

    def test_get_groups_members(self):
        """Test case for get_groups_members

        Get Members of multiple groups  # noqa: E501
        """
        pass

    def test_remove_group_member(self):
        """Test case for remove_group_member

        Remove a group member  # noqa: E501
        """
        pass

    def test_remove_group_member_by_person_uid(self):
        """Test case for remove_group_member_by_person_uid

        Remove a group member by person uid  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
