# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.wrapped_group_member import WrappedGroupMember  # noqa: E501
from swagger_client.rest import ApiException


class TestWrappedGroupMember(unittest.TestCase):
    """WrappedGroupMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWrappedGroupMember(self):
        """Test WrappedGroupMember"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.wrapped_group_member.WrappedGroupMember()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
