# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.orgs_api import OrgsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOrgsApi(unittest.TestCase):
    """OrgsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.orgs_api.OrgsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_org(self):
        """Test case for create_org

        Create org  # noqa: E501
        """
        pass

    def test_find_orgs(self):
        """Test case for find_orgs

        Find org  # noqa: E501
        """
        pass

    def test_get_org(self):
        """Test case for get_org

        Get org  # noqa: E501
        """
        pass

    def test_update_org(self):
        """Test case for update_org

        Update org  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
