# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.consents_api import ConsentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConsentsApi(unittest.TestCase):
    """ConsentsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.consents_api.ConsentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_consent(self):
        """Test case for create_consent

        Create consent  # noqa: E501
        """
        pass

    def test_find_consents(self):
        """Test case for find_consents

        Find consents  # noqa: E501
        """
        pass

    def test_get_consent(self):
        """Test case for get_consent

        Get consent  # noqa: E501
        """
        pass

    def test_update_consent(self):
        """Test case for update_consent

        Update consent  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
