# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.affiliations_api import AffiliationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAffiliationsApi(unittest.TestCase):
    """AffiliationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.affiliations_api.AffiliationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_affiliation(self):
        """Test case for create_affiliation

        Create affiliation  # noqa: E501
        """
        pass

    def test_find_affiliations(self):
        """Test case for find_affiliations

        Get affiliation  # noqa: E501
        """
        pass

    def test_get_affiliation(self):
        """Test case for get_affiliation

        Get affiliation  # noqa: E501
        """
        pass

    def test_remove_affiliation(self):
        """Test case for remove_affiliation

        Remove affiliation  # noqa: E501
        """
        pass

    def test_update_affiliation(self):
        """Test case for update_affiliation

        Update affiliation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
