# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.role_assignments_api import RoleAssignmentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRoleAssignmentsApi(unittest.TestCase):
    """RoleAssignmentsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.role_assignments_api.RoleAssignmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_role_assignment(self):
        """Test case for create_role_assignment

        Create role assignment  # noqa: E501
        """
        pass

    def test_find_role_assignments(self):
        """Test case for find_role_assignments

        Get role assignment  # noqa: E501
        """
        pass

    def test_get_role_assignment(self):
        """Test case for get_role_assignment

        Get role assignment  # noqa: E501
        """
        pass

    def test_remove_role_assignment(self):
        """Test case for remove_role_assignment

        Remove role assignment  # noqa: E501
        """
        pass

    def test_update_role_assignment(self):
        """Test case for update_role_assignment

        Update role assignment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
