# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.wrapped_role_assignment import WrappedRoleAssignment  # noqa: E501
from swagger_client.rest import ApiException


class TestWrappedRoleAssignment(unittest.TestCase):
    """WrappedRoleAssignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWrappedRoleAssignment(self):
        """Test WrappedRoleAssignment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.wrapped_role_assignment.WrappedRoleAssignment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
