# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.roles_api import RolesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.roles_api.RolesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_role(self):
        """Test case for create_role

        Create role  # noqa: E501
        """
        pass

    def test_find_roles(self):
        """Test case for find_roles

        Find role  # noqa: E501
        """
        pass

    def test_get_role(self):
        """Test case for get_role

        Get role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
