# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.countries_api import CountriesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCountriesApi(unittest.TestCase):
    """CountriesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.countries_api.CountriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_country(self):
        """Test case for create_country

        Create country  # noqa: E501
        """
        pass

    def test_find_countries(self):
        """Test case for find_countries

        Find country  # noqa: E501
        """
        pass

    def test_get_country(self):
        """Test case for get_country

        Get country  # noqa: E501
        """
        pass

    def test_update_country(self):
        """Test case for update_country

        Update country  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
