# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.persons_api import PersonsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPersonsApi(unittest.TestCase):
    """PersonsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.persons_api.PersonsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_group_memberships(self):
        """Test case for check_group_memberships

        Check group memberships for a person  # noqa: E501
        """
        pass

    def test_check_group_memberships_person(self):
        """Test case for check_group_memberships_person

        Check group memberships for a person (legacy endpoint)  # noqa: E501
        """
        pass

    def test_create_persons(self):
        """Test case for create_persons

        Create person  # noqa: E501
        """
        pass

    def test_find_persons(self):
        """Test case for find_persons

        Find person  # noqa: E501
        """
        pass

    def test_get_person(self):
        """Test case for get_person

        Get person  # noqa: E501
        """
        pass

    def test_get_person_id(self):
        """Test case for get_person_id

        Get personID  # noqa: E501
        """
        pass

    def test_remove_person(self):
        """Test case for remove_person

        Remove person  # noqa: E501
        """
        pass

    def test_update_person(self):
        """Test case for update_person

        Update person  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
