# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.wrapped_with_meta_array_group_member import WrappedWithMetaArrayGroupMember  # noqa: E501
from swagger_client.rest import ApiException


class TestWrappedWithMetaArrayGroupMember(unittest.TestCase):
    """WrappedWithMetaArrayGroupMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWrappedWithMetaArrayGroupMember(self):
        """Test WrappedWithMetaArrayGroupMember"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.wrapped_with_meta_array_group_member.WrappedWithMetaArrayGroupMember()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
