# coding: utf-8

"""
    BCC Core API

    This is the Core API  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.groups_api import GroupsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.groups_api.GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_group(self):
        """Test case for create_group

        Create group  # noqa: E501
        """
        pass

    def test_find_groups(self):
        """Test case for find_groups

        Find group  # noqa: E501
        """
        pass

    def test_get_group(self):
        """Test case for get_group

        Get group  # noqa: E501
        """
        pass

    def test_remove_group(self):
        """Test case for remove_group

        Remove group  # noqa: E501
        """
        pass

    def test_update_group(self):
        """Test case for update_group

        Update group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
